public class SampleClass1 {
    public void printSomeString() {
        if (true) {
            if (true) {
                if (true) {
                    if (true) {
                        if (true) {
                            if (true) {
                                System.debug('Hello!');
                            }
                        }
                    }
                }
            }
        }
    }
}